### PR TITLE
Add TypeScript type declarations

### PR DESCRIPTION
**Pull request by ukstv**
Here is a volunteered TypeScript declaration.

### CODE REVIEW

**Comment by feross** [comment]
LGTM

**Comment by feross** [comment]
Released as 5.1.2

**Comment by feross** [comment]
@ukstv Would you mind sending a similar PR for the [`buffer`](https://github.com/feross/buffer) package?

**Comment by ukstv** [comment]
Ok.

**Comment by ukstv** [comment]
Super cool the declarations are released!

**Comment by ukstv** [comment]
https://github.com/feross/buffer/pull/194 Here is a pull request to `buffer` package.

**Comment by feross** [comment]
Thanks @ukstv, super appreciate it! I'm going to add you as a GitHub collaborator to the `safe-buffer` and the `buffer` repo. It would be great if you could keep the TypeScript types up-to-date. There aren't that many API changes, but I imagine there may be some changes in the future.

**Comment by ukstv** [comment]
@feross You are welcome!

**Pull request merged**
