### PR TITLE
Add buffer dep

### PR DESCRIPTION
**Pull request by jreading**
#9

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
i think the errors are unrelated so this looks good

**Comment by toddself** [comment]
It would be awesome to get this merged in.  We're using an older browserify so getting the buffer.alloc error, especially since the errors seem to be just the deprecation warning?

**Comment by dcousens** [comment]
Wouldn't this mean node versions would also be downloading `buffer`?
I don't think we want that.

**Comment by dcousens** [comment]
@feross what's do you think?

**Comment by toddself** [comment]
@dcousens you can provide a different file for bundlers vs node using the "browser" field.

```json
"browser":  {
    "buffer": "./some/buffer-shim.js"
}
```

So long as the bundler uses the [spec](https://github.com/defunctzombie/package-browser-field-spec) it should do the right thing.

**Comment by dcousens** [comment]
@toddself the issue isn't browser using the wrong version, its node... see #11

**Comment by toddself** [comment]
Our error was in the browser:  Buffer.alloc was being called by browser crypto but we were on browserify 10. The buffer module included with that version of browserify doesn't include alloc. 

We had to upgrade browserify to get a newer buffer. This would have been solved if safe-buffer had a dependency on a buffer module since it would have included its own version that has the alloc call.

**Comment by dcousens** [comment]
@toddself I understand,  this PR needs to merged,  but only if #11 is merged too.
Otherwise you screw the node users.

**Comment by feross** [comment]
This was fixed by #12 and released as 5.1.0.

**Pull request closed without merging**
